### PR TITLE
fixed server file to access both webRouter and ussdRouter. Created a …

### PR DESCRIPTION
**Pull request by nevets615**
…put and a delete endpoint. tested and functioning

### CODE REVIEW

**Review by ohheyimjen — DISMISSED** [review]
thumbs up emoji

**Review by cammac725 — DISMISSED** [review]

**Review by CleverOscar — DISMISSED** [review]
I am trying to solve the merge conflict, don't merge yet

**Review by nevets615 — COMMENTED** [review]
perfect

**Review by nevets615 — COMMENTED** [review]
this should be right

**Review by cammac725 — APPROVED** [review]

**Pull request merged**
