### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by VivaCode**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I find this to be ok

**Review by chef27615 — APPROVED** [review]
gtg

**Review by cammac725 — COMMENTED** [review]
Approve

**Review by ohheyimjen — APPROVED** [review]
looks great!

**Review by sarahrileydev — APPROVED** [review]

**Review by nevets615 — APPROVED** [review]

**Review by CleverOscar — COMMENTED** [review]
Remarkable

**Pull request merged**
